-- MySQL Script generated by MySQL Workbench
-- Sat Sep 30 14:41:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema miu_session_laravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miu_session_laravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miu_session_laravel` DEFAULT CHARACTER SET utf8 ;
USE `miu_session_laravel` ;

-- -----------------------------------------------------
-- Table `miu_session_laravel`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miu_session_laravel`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `image` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miu_session_laravel`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miu_session_laravel`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `image` TINYTEXT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_genre_idx` (`genre_id` ASC),
  CONSTRAINT `fk_movie_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `miu_session_laravel`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
